---
- name: add lxd ppa
  apt_repository: repo='ppa:ubuntu-lxc/lxd-git-master'

- name: packages update
  apt: update_cache=yes

- name: lxd install
  apt: name={{item}} state=present
  with_items:
    - lxd

- name: enable lxd services
  service: name={{item}} state=started enabled=yes
  with_items:
    - lxd
